#!/bin/bash

pip install .
jupyter nbextension     enable --py --sys-prefix appmode
jupyter serverextension enable --py --sys-prefix appmode
jupyter nbextension enable --py --sys-prefix widgetsnbextension


#EOF
